export const SEARCH_SYMBOL = 'SEARCH_SYMBOL';
export const FETCH_SYMBOL_SUCCESS = 'FETCH_SYMBOL_SUCCESS';
export const ADD_WATCHLIST = 'ADD_WATCHLIST';
export const DELETE_WATCHLIST = 'DELETE_WATCHLIST';
export const FETCH_FOCUS_SUCCESS = "FETCH_FOCUS_SUCCESS";
export const FETCH_FOCUS_FAIL = "FETCH_FOCUS_FAIL";
export const SHOW_WATCHLIST = 'SHOW_WATCHLIST';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';