export const SEARCH_SYMBOL = 'SEARCH_SYMBOL';
export const FETCH_SYMBOL_SUCCESS = 'FETCH_SYMBOL_SUCCESS';
export const ADD_WATCHLIST = 'ADD_WATCHLIST';
export const DELETE_WATCHLIST = 'DELETE_WATCHLIST';
export const FETCH_FOCUS_SUCCESS = "FETCH_FOCUS_SUCCESS";
export const FETCH_FOCUS_FAIL = "FETCH_FOCUS_FAIL";
export const SHOW_WATCHLIST = 'SHOW_WATCHLIST';